[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 12.0
normal = { family = "Fira Code" }
bold = { family = "Fira Code", style = "Bold" }
italic = { family = "Fira Code", style = "Italic" }
bold_italic = { family = "Fira Code", style = "Bold Italic" }

[window]
padding = { x = 8, y = 8 }

[cursor]
style = "Beam"
blink_interval = 750
blink_timeout = 0

